# This CI/CD Pipeline does not actually work. I set it up as a placeholder
# since this would be the next step during my development process of the EMS
# system.

name: CI/CD Pipeline

on:
  push:
    branches:
      - does-not-work-placeholder-only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Export new environment variables
      - name: Export new environment variables
        run: |
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> $GITHUB_ENV
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV
          echo "REDIS_DB=${{ secrets.REDIS_DB }}" >> $GITHUB_ENV
          echo "REDIS_PASS=${{ secrets.REDIS_PASS }}" >> $GITHUB_ENV
          echo "WS_HOST=${{ secrets.WS_HOST }}" >> $GITHUB_ENV
          echo "WS_PORT=${{ secrets.WS_PORT }}" >> $GITHUB_ENV

      # Install dependencies with Pipenv
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      # Lint code with pylint
      - name: Lint code with pylint
        run: |
          pipenv run pylint .

      # Run tests with pytest
      - name: Run tests with pytest
        run: |
          pipenv run pytest -v

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-app-name:latest .

      # Push Docker image to registry
      - name: Push Docker image to Docker Hub
        run: |
          docker push your-dockerhub-username/your-app-name:latest

      # Notify central server of new image so it can push to a kafka topic
      # which can update the Microservice via a rolling update.
      - name: Notify Central Server
        run: |
          curl -X POST https://your-central-server
          .com/notify/WebsocketServerMS \
            -H "Content-Type: application/json" \
            -d '{"image": "your-dockerhub-username/your-app-name:latest"}'
